SELECT SKU,SKU_DESCRIPTION FROM INVENTORY;
SELECT SKU_Description, SKU FROM INVENTORY;
SELECT WarehouseID FROM INVENTORY;
SELECT DISTINCT WarehouseID FROM INVENTORY;
SELECT * from INVENTORY WHERE QUANTITYONHAND > 0;